### ISSUE TITLE
add/edit/delete project does not reload page automatically

### ISSUE THREAD

**Issue by tstejl** [biu-engineering/biu#21]
in feature_user branch

**Comment by tstejl** [comment]
user_feature branch

**Comment by tstejl** [comment]
rt

**Comment by magickaichen** [comment]
#20

**Comment by jouhyoung** [comment]
notes: we can pass the function to add/edit/delete down the component so we can trigger the changes to reflect in React without reloading the page.

**Comment by magickaichen** [comment]
Closing this issue since this has been fixed in #22
